### PR TITLE
Update ashram_poudel.md

### PR DESCRIPTION
**Pull request by theonlyNischal**

### CODE REVIEW

**Comment by MegaMind98** [comment]
Cannot verify the authenticity of the information provided, @Aakrist36!

**Comment by theonlyNischal** [comment]
You can testify it yourself

**Comment by MegaMind98** [comment]
We will ask him on class. How about that? Lol

**Comment by theonlyNischal** [comment]
hahaha

**Comment by theonlyNischal** [comment]
Hey What about the email id classof2020@gmail.com,
Every of us don't have ownership on it , we cannot let you to misuse the
name of our community.
It would be really nice of it  if you share the information
Sincerely,
Nischal Lal Shrestha

**Comment by MegaMind98** [comment]
Hello. 

I'm creating a new issue. Check #23

**Comment by theonlyNischal** [comment]
which issue?

**Pull request closed without merging**
